### ISSUE TITLE
Follow Semver - Please

### ISSUE THREAD

**Issue by umerkk** [reZach/i18next-electron-fs-backend#11]
Hi
I hope you all know that the latest release of this library 1.3.9 was a breaking change for anyone using your library.

The consequences of just `BUMPING THE DEPENDENCIES` has been fatal and I would appreciated if the release has been tagged major or at least communicated clearly.

The introduction of `process` object in `reloadBindings` function broke our existing application (that wasn't required before).

Keep doing the great work.

**Comment by reZach** [comment]
Thanks @umerkk. This was my mistake - I do hope this wasn't a mission-critical application that was fatal (I haven't heard of a single person using this library in production cases yet). I've got a [new release](https://github.com/reZach/i18next-electron-fs-backend/releases/tag/v2.0.0) that has the version bumped properly.

**Comment by umerkk** [comment]
Thanks for the new release. Much appreciated :-) 

On the other hand, I can confirm, that we are looking into using this library in one of our production app.
