### ISSUE TITLE
Using contextBridge with "apiKey" other than "api" not allowed and not throwing clear error 

### ISSUE THREAD

**Issue by Ciberusps** [reZach/i18next-electron-fs-backend#14]
Using contextBridge with "apiKey" other than "api" not allowed and not throwing clear error 
So I lost a lot of time to get why i receive these error `Cannot read properties of undefined (reading 'i18nextElectronBackend')`

![image](https://user-images.githubusercontent.com/14001879/178735116-c7168a6e-36b7-43cb-8d7c-0711d9aff39b.png)

It was because i use `contextBridge.exposeInMainWorld("electron", api);` `electron` for `apiKey` in contextBridge, but in `i18next-electron-fs-backend` all hardcoded to `window.api`. And that leads to strange not clear error.

![image](https://user-images.githubusercontent.com/14001879/178733475-69736947-06e4-4505-8a94-0c716e6d4037.png)

Also `ipcRenderer` option misslead a lot, cause i thought it will be using object i provided `ipcRenderer: window.electron.i18nextElectronBackend` but its using `window.api`

![image](https://user-images.githubusercontent.com/14001879/178737722-617f0392-1837-49cf-817e-cb022b1156fc.png)

I wanted to make pull request, but dont know what to do better:
1) warn people using contextBridge `apiKey` stricted only to "api", in such case `ipcRenderer` option not required cause we always know that its in `window.api.i18nextElectronBackend`
2) add param to `backend.mainBindings` with custom `apiKey` for `contextBridge`

**Comment by reZach** [comment]
Thanks for this issue, @Ciberusps. I agree this is confusing and the package _was_ defaulting/expecting "api" to be used in the contextBridge call. I've [pushed a release](https://github.com/reZach/i18next-electron-fs-backend/releases/tag/v3.0.0) that will allow you to configure this key value. Let me know if you have issues and/or if we need to re-open this issue.
