### ISSUE TITLE
Getting Error when enforcing Electron App to move to Application Folder

### ISSUE THREAD

**Issue by mrgodhani** [reZach/i18next-electron-fs-backend#6]
Hi

I am noticing an error when the application moves to the Application Folder on app start/boot. Noticing this is only happening for Electron version > 12.0.3 and if I remove main binding call i.e `backend.mainBindings(ipcMain, win, fs); // <- configures the backend` then I don't see that error dialog. For moving application to application folder I am using https://github.com/sindresorhus/electron-util `enforceMacOSAppLocation()` function.

Following is the error I am getting:

```
TypeError: Object has been destroyed
at BrowserWindow.<anonymous> (/Users/johndoe/Projects/example-app/dist_electron/mac/Example App.app/Contents/Resources/app.asar/background.js:2:580450)
at electron/js2c/asar_bundle.js:5:507
at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

The above error also triggers on packaged applications and not in the development environment.  The above error does not break the app it still moves to the Application Folder but cannot seem to find a way to solve the above issue of removing that error that keeps on showing on app move.

Steps to Reproduce:

-  Use electron version 12.0.3 or above
- Use enforceMacOSAppLocation() to move app
- Call i18next backend binding on creating window.
- Build the app and start the application folder from folder outside "Application" in Mac OS.

**Comment by reZach** [comment]
@mrgodhani Thanks for opening the issue.

When the package loads, the [path to the translation files are fixed](https://github.com/reZach/i18next-electron-fs-backend/blob/master/src/index.js#L13-L14), that is why I suspect you are encountering the error when you call `enforceMacOSAppLocation()`. The most reasonable fix while thinking of this is if `enforceMacOSAppLocation()` returned a promise, and then once that call is finished, you'd be able to pass in the appropriate path in the options when configuring i18n, ie:

```js
import i18n from "i18next";
import {
  initReactI18next
} from "react-i18next";
import backend from "i18next-electron-fs-backend";

i18n
  .use(backend)
  .use(initReactI18next)
  .init({
    backend: {
      loadPath: "./app/localization/locales/{{lng}}/{{ns}}.json", // < HERE
      addPath: "./app/localization/locales/{{lng}}/{{ns}}.missing.json", // < HERE
      ipcRenderer: window.api.i18nextElectronBackend
    },

    // other options you might configure
    debug: true,
    saveMissing: true,
    saveMissingTo: "current",
    lng: "en"
  });

export default i18n;
```

**Comment by mrgodhani** [comment]
https://github.com/sindresorhus/electron-util/blob/main/source/enforce-macos-app-location.js Don't think enforceMacOSAppLocation() returns a promise.

**Comment by reZach** [comment]
@mrgodhani My suggestion is that the **electron-util** library needs to change in order to support **i18next-electron-fs-backend** working with `enforceMacOSAppLocation`. Unless there is another solution available that we haven't thought of yet.

**Comment by mrgodhani** [comment]
Closing it seems to be working okay now. Issue probably is due to electron builder v22.11.*
