### ISSUE TITLE
Property 'api' does not exist on type 'Window & typeof globalThis'.

### ISSUE THREAD

**Issue by timebuzzerfelix** [reZach/i18next-electron-fs-backend#7]
Hi

iIn our app "api" males trouble:

![image](https://user-images.githubusercontent.com/70972064/122679715-3bc22b80-d1ec-11eb-9380-3e2fb69bc106.png)

we are not using React, maybe this is the reason?

**Comment by reZach** [comment]
@timebuzzerfelix This is defined in the `preload.js` file, have you altered that file?

**Comment by timebuzzerfelix** [comment]
thanks for your answer. This is the preload.ts: 

![image](https://user-images.githubusercontent.com/70972064/123306273-5c0e2500-d521-11eb-9700-a6d14697b8ff.png)

**Comment by reZach** [comment]
Are you using [secure-electron-template](https://github.com/reZach/secure-electron-template) or something else @timebuzzerfelix ?

**Comment by egll-tech** [comment]
create a `<WHATEVER>.d.ts` file and add this
```
declare global {
  interface Window {
    api?: any;
  }
}
```

**Comment by reZach** [comment]
@timebuzzerfelix I am assuming you found the solution to your question. If you _have_, it would be helpful to share that solution here, otherwise please feel free to re-open this issue if your problem persists.

**Comment by timebuzzerfelix** [comment]
Hi, sorry for late answer. What might help is to set `contextIsolation: true`
But in our case we build our own translation module, so I can't say for sure
